---
name: docker
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: hsmtkk/verbose-umbrella
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
      - name: Push To docker.io
        id: push-to-docker
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io
          username: hsmtkk
          password: ${{ secrets.REGISTRY_PASSWORD }}
