---
name: Rust
on: [push]  # yamllint disable-line rule:truthy
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: audit
        run: cargo audit
      - name: clippy
        run: cargo clippy
